version: "3.4"


services:
  clam:
    # Clamd lives on port 3310
    image: docker.pkg.github.com/churchdesk/docker-clamav/image:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1 # The number of containers to update at a time.
        delay: 260s # The time to wait between updating a group of containers.
        monitor: 300s
        order: start-first
    environment:
      - CLAMD_SETTINGS_CSV=StreamMaxLength=50M
    networks:
      - internal
    healthcheck:
      test: ["CMD", "/readyness.sh"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 240s

networks:
  internal:
    external: true
